# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.sepolia]
url = "https://api.cartridge.gg/x/starknet/sepolia"
accounts-file = "../account-sepolia.json"
account = "deployer"
